### ISSUE TITLE
my contract dont display Buy price

### ISSUE THREAD

**Issue by bboynam99** [crosspunks/crosspunks-app#1]
I deployed my own contract
Could anyone please explain why when i sale items, they dont display "Cancel Selling" button and "Buy" button??

**Comment by deadblackclover** [comment]
These two buttons are in the same condition depending on whether the user is the owner or not.

Here's the problem:
![Screenshot_20211125_212248](https://user-images.githubusercontent.com/26848022/143458475-b94145cf-6be2-4c63-91cd-5739a3d20e09.png)

We will try to fix it in the near future. Thx!

**Comment by bboynam99** [comment]
Thank you for your time
This is a cool script

**Comment by deadblackclover** [comment]
Fixed!
https://github.com/crosspunks/crosspunks-app/commit/1ca00abe6a6e03ac43461b705329a6aff89a50f3
